import './globals.css';
import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
    title: 'Create Next App',
    description: 'Generated by create next app',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
    return (
        <html lang="en">
            <body className={inter.className}>
                <header className="container mx-auto px-4 pt-4 pb-4">
                    <h1 className="text-4xl">Exercise 048</h1>
                </header>
                <main className="container mx-auto px-4 pb-8">{children}</main>
            </body>
        </html>
    );
}
